### PR TITLE
Fixes the missing certificate id from the certificate purchase struct

### PR DESCRIPTION
**Pull request by ecomba**
This PR fixes the issue in where the certificate id was not picked up when purchasing a certificate

### CODE REVIEW

**Review by DXTimer — APPROVED** [review]
💯 :shipit:

**Comment by weppos** [comment]
Added the "bug" type label.

**Review by weppos — APPROVED** [review]

**Comment by weppos** [comment]
I suggest to update also the CHANGELOG upon merge.

**Comment by ecomba** [comment]
> I suggest to update also the CHANGELOG upon merge.

That was the plan!

**Pull request merged**
