### PR TITLE
Don't send Content-Type header for requests w/o a body

### PR DESCRIPTION
**Pull request by jodosha**
Ref #55

### CODE REVIEW

**Comment by aeden** [comment]
What happens when the content-type header is sent without a body? Isn't it simply ignored?

**Comment by jodosha** [comment]
@aeden Yes

**Comment by aeden** [comment]
Given that it is ignored, is this change actually necessary? Is there a benefit from only sending it when their is body data?

**Comment by jodosha** [comment]
@aeden Not harmful, but useless.

It shouldn't always be sent because that header is metadata that advertises the server on how to interpret the body. But in case the body is missing, the header is useless.

---

One of the goals of our clients is to serve as an example of strict use of the API. Also, in the Ruby client we already perform this check to decide if send the header or not.

**Comment by weppos** [comment]
I wonder if this change may cause more issues that what tries to fix. FYI sending the content type even for empty body is not forbidden.
https://stackoverflow.com/questions/29784398/should-content-type-header-be-present-when-the-message-body-is-empty

I am torn. We may end up increasing the complexity of the client and potentially causing bugs where the content type is not sent for some specific unknown cases.

**Comment by weppos** [comment]
Sorry, closed by mistake.

**Comment by jodosha** [comment]
Given 2 out 2 reviews are against this change, I'm closing this PR.

---

@weppos Do we need to change the Ruby client to make it to always send the `Content-Type` header? As now, the version `4.1.0` sends that header only if there is a request payload.

**Pull request closed without merging**
